spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/security-prac
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      # ??? ? ??? ??? ?? (???? create-drop)
    properties:
      hibernate:
        # show_sql: true -> printf ??? sql ??
        format_sql: true

  security:
    user:
      name: user
      password: 1111
      roles: USER

logging.level:
  org.hibernate.SQL: debug