spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
      diver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        use_sql_comments: true
        # ↑실행되는 쿼리를 Teminal에서 주석으로 보여줌.

# 새로 추가된 문장 ↓
  profiles:
    active: local
# 새로 추가된 문장 ↑

logging.level:
  org.hibernate.SQL: debug
  #org.hibernate.type: trace